---
- name: Fail if molecule group is missing
  hosts: localhost
  tasks:
    - name: Print some info
      ansible.builtin.debug:
        msg: "{{ groups }}"

    - name: Assert group existence
      ansible.builtin.assert:
        that: "'molecule' in groups"
        fail_msg: |
          molecule group was not found inside inventory groups: {{ groups }}

- name: Converge
  hosts: molecule
  # We disable gather facts because it would fail due to our container not
  # having python installed. This will not prevent use from running 'raw'
  # commands. Most molecule users are expected to use containers that already
  # have python installed in order to avoid notable delays installing it.
  gather_facts: false
  tasks:
    - name: Check uname
      ansible.builtin.raw: uname -a
      register: result
      changed_when: false

    - name: Print some info
      ansible.builtin.assert:
        that: result.stdout | regex_search("^Linux")

    - name: Create test users
      ansible.builtin.include_role:
        name: users
      vars:
        server_users:
          - username: testadmin
            admin: true
            state: present
            password: $5$M8PNjsAxVb2QqRzN$jH7YgbvE/4kO7SRBCPYDP69OJV0aDQVMoig8aKoLAfD
          - username: testuser
            state: present
            ssh_keys:
              - "ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABgQC6enYRSK7kBwD+KHU1OVBpHjz3iRA5DW4PPacZmRHxvxJ2H2gRVnqB38hgEbm1LkPOjI1b/S5kMGI4gMeHWe4CUFYoyVcyMyyDPNdGArDZErz5cGoMEE/9319p5O6lTLWh7omrR2cAEMU8mQ3zfvPxk2OvzGaG834tfu0POpGk5xIj0cqxyUQn7vy1GSu+E0aMql/jK0HahSSMdqk4B8x1dHhvpd17ZYA37NMjUBuhc7vClxoufxkjKxAIoLL/Tx79H2CoQ9OtE/u/Z5X9t3NLdy1+wuSgV+TD7ib1cHnGtCQ4/8625l/2rVRnU/jfApRTrkrv1Fhu1H5p6eKEwjJQ29CEUKFeQLM1NluIJVWWhLXTg3ec0MHOrAr8I/bZECeNB5qRZTfQSfkcXjqfNGoVVoXIqCGIFY6ULQqd9OoGYrBpOG/LfH2Ly5P9aHAHoZZ+dEi8QcRYqPyQmqg815v/dvMDeN5Ohr8sCHOR2TcnE6Hj7IcTm0yo8gKMl1hLCuc= testuser@molecule"

    - name: Test user authentication
      vars:
        testadmin_pw: test123
      block:
        - name: Attempt admin logon
          become: true
          become_user: testuser
          ansible.builtin.shell:
            cmd: echo {{ testadmin_pw }} | su - testadmin -c 'echo success'
          register: testadmin_login_result
          changed_when: false

        - name: Show login output
          ansible.builtin.debug:
            msg: "{{ testadmin_login_result.stdout }}"
        - name: Attempt ssh login with key
          block:
            - name: Openssh is installed
              become: true
              ansible.builtin.package:
                name: openssh-clients
                state: present

            - name: SSH key exists on host
              ansible.builtin.copy:
                src: "{{ playbook_dir }}/files/testuser"
                dest: /tmp/testuser
                mode: 0600

            - name: Attempt ssh login
              ansible.builtin.command:
                cmd: ssh -i /tmp/testuser testuser@localhost 'echo success'
              register: testuser_ssh_result
              changed_when: false

            - name: Show ssh login output
              ansible.builtin.debug:
                msg: "{{ testuser_ssh_result.stdout }}"

