---
role_name_check: ${MOLECULE_ROLE_NAME_CHECK:-0}
dependency:
  name: galaxy
driver:
  name: default
  options:
    managed: true
    login_cmd_template: 'docker exec -ti {instance} bash'
platforms:
  - name: instance
    image: "geerlingguy/docker-${MOLECULE_DISTRO:-rockylinux9}-ansible:latest"
    modify_image: false
    dockerfile: files/Dockerfile
    command: ${MOLECULE_DOCKER_COMMAND:-""}
    volumes:
      - /sys/fs/cgroup/molecule-ci.scope:/sys/fs/cgroup:rw
    cgroupns_mode: host
    privileged: false
    tmpfs:
      - /run
provisioner:
  name: ansible
  playbooks:
    prepare: ${MOLECULE_PLAYBOOK:-prepare.yml}
    converge: ${MOLECULE_PLAYBOOK:-converge.yml}
  config_options:
    defaults:
      gathering: explicit
      vault_password_file: ~/.ansible/molecule-ci.pw

