---
role_name_check: ${MOLECULE_ROLE_NAME_CHECK:-0}
dependency:
  name: galaxy
driver:
  name: default
  options:
    managed: true
    login_cmd_template: 'docker exec -ti {instance} bash'
platforms:
  - name: instance
    image: "geerlingguy/docker-${MOLECULE_DISTRO:-rockylinux9}-ansible:latest"
    command: ${MOLECULE_DOCKER_COMMAND:-sleep 1d}
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:rw
    cgroupns_mode: host
    privileged: true
    pre_build_image: true
    tmpfs:
      - /run
      - /tmp
provisioner:
  name: ansible
  playbooks:
    prepare: ${MOLECULE_PLAYBOOK:-prepare.yml}
    converge: ${MOLECULE_PLAYBOOK:-converge.yml}
  config_options:
    defaults:
      gathering: explicit

