---
# tasks file for users

- name: Load ansible environment vars
  ansible.builtin.setup:
    gather_subset:
      - "!all"
      - "!min"
      - date_time
      - user
    filter:
      - ansible_user_id
      - ansible_date_time*

- name: Show date time facts
  ansible.builtin.debug:
    var: ansible_date_time

- name: Make the users 👌
  vars:
    __user_managed_accounts: "{{ server_users | rejectattr('username', 'eq', ansible_user_id) }}"
    __user_present_accounts: "{{ __user_managed_accounts | rejectattr('state', 'eq', 'absent') }}"
    __user_absent_accounts: "{{ __user_managed_accounts | selectattr('state', 'eq', 'absent') }}"
  block:
    - name: Warn about currently logged on user
      loop: "{{ server_users | selectattr('state', 'eq', 'absent') | selectattr('username', 'eq', ansible_user_id)}}"
      loop_control:
        loop_var: __user_current_user
        label: "{{ __user_current_user.username }}"
      ansible.builtin.debug:
          msg: ⚠ Not removing user {{ __user_current_user.username }} because we are currently running as that user!

    - name: Manage user groups
      ansible.builtin.include_tasks: groups.yml

    - name: Manage user accounts
      ansible.builtin.include_tasks: users.yml

    - name: Manage user ssh keys
      vars:
        __user_ssh_accounts: >
          {{
            __user_present_accounts | selectattr('ssh_keys', 'defined') | default([]) +
            __user_present_accounts | selectattr('ssh_private_key', 'defined') | default([])
          }}
      ansible.builtin.include_tasks: ssh.yml

    - name: Manage user sudo access
      ansible.builtin.include_tasks: sudo.yml

    - name: Manage robot user customizations
      vars:
        __user_robot_accounts: "{{ __user_present_accounts | selectattr('username', 'eq', 'robot') | list }}"
      ansible.builtin.include_tasks: robot.yml

