---

- name: Retrieve container log
  ansible.builtin.command:
    cmd: docker logs {{ item.container.Name }}
  changed_when: false
  register: logfile_cmd

- name: Display container log
  ansible.builtin.fail:
    msg: "{{ logfile_cmd.stdout ~  logfile_cmd.stderr }}"

