---
- name: Create
  hosts: localhost
  gather_facts: false
  tasks:
    - name: Create platform
      ansible.builtin.include_role:
        name: syndr.molecule.docker_platform
      vars:
        docker_platform_name: "{{ item.name }}"
        docker_platform_image: "{{ item.image }}"
        docker_platform_systemd: "{{ item.systemd | default(false) }}"
        docker_platform_modify_image: "{{ item.modify_image | default(false) }}"
        docker_platform_privileged: "{{ item.privileged | default (false) }}"
        docker_platform_state: present
      loop: "{{ molecule_yml.platforms }}"
      loop_control:
        label: item.name

# We want to avoid errors like "Failed to create temporary directory"
- name: Validate that inventory was refreshed
  hosts: molecule
  gather_facts: false
  tasks:
    - name: Check uname
      ansible.builtin.raw: uname -a
      register: result
      changed_when: false

    - name: Display uname info
      ansible.builtin.debug:
        msg: "{{ result.stdout }}"

