---

name: Deploy Role
on:
  release:
    types:
      - created
jobs:
  deploy:
    runs-on: ubuntu-latest
    if: |
      github.event.release.prerelase == false
    steps:
      - uses: actions/checkout@v4

      - name: Build and Deploy Role
        uses: averagebit/action-galaxy@1.0.0
        with:
          galaxy_token: '${{ secrets.GALAXY_API_KEY }}'

