---

name: Role - users
on:
  pull_request:
  push:
    branches:
      - main
    paths:
      - '.github/workflows/role-users.yml'
      - './**'
      - '!*.md'
  schedule:
    - cron: '13 13 * * 0'

jobs:
  build-system:
    name: "Role: users"
    strategy:
      max-parallel: 4
      fail-fast: false
      matrix:
        python-version: ["3.12"]
        molecule-scenario:
          - role-users-docker

    if: >
      (github.event_name == 'pull_request' ||
      (github.event_name == 'push' && github.ref_name == 'main'))
    uses: ./.github/workflows/_run-molecule-test.yml
    with:
      scenario: ${{ matrix.molecule-scenario }}
      python-version: ${{ matrix.python-version }}
    secrets: inherit

  deploy-system:
    runs-on: ubuntu-latest
    needs: build-system
    if: github.event_name == 'push'
    steps:
      - uses: actions/checkout@v4

      - name: Create and Push Tag
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          set -e
          TAG_NAME=${{ github.ref_name }}
          echo "Creating tag $TAG_NAME"
          # Configure Git user
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          # Create the tag
          git tag "$TAG_NAME"
          # Push the tag to the repository
          git push origin "refs/tags/$TAG_NAME" --force

